import type { FullProduct } from './products-fallback';

export const WOODEN_DECOR_PRODUCTS: FullProduct[] = [
  {
    id: 'dec_1',
    slug: 'kyoto-solid-walnut-sculptural-bowl',
    name: 'The Kyoto Sculptural Walnut Centerpiece Bowl',
    tagline: 'Hand-turned from a single block of old-growth American walnut',
    description: 'Carved by master artisans, this monolithic bowl highlights the undulating heartwood grain of sustainable walnut. Hand-rubbed with organic tung oil and food-grade beeswax.',
    category: 'Decor',
    dimensions: 'Diameter: 42cm | H: 14cm | Weight: 3.8kg',
    warranty: '10 Years Wood Integrity Guarantee',
    careInstructions: 'Wipe with a soft microfibre cloth. Condition semi-annually with pure mineral or walnut oil.',
    basePrice: 24500,
    featured: true,
    hsnCode: '9403',
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?auto=format&fit=crop&w=1200&q=80',
    ]),
    variants: [
      { id: 'vd_1', sku: 'DEC-BWL-WAL-NAT', colorName: 'Natural Walnut', colorHex: '#5C3A21', material: 'Solid American Walnut', priceOverride: 24500, stock: 8 },
      { id: 'vd_2', sku: 'DEC-BWL-WAL-EBO', colorName: 'Smoked Ebony', colorHex: '#221F1D', material: 'Smoked Black Walnut', priceOverride: 26500, stock: 4 },
    ],
  },
  {
    id: 'dec_2',
    slug: 'solaria-hand-carved-teak-wall-panel',
    name: 'The Solaria Jodhpur Jali Carved Teak Wall Panel',
    tagline: 'Architectural lattice fretwork carved from seasoned reclaimed teak',
    description: 'Inspired by the regal courtyards of Mehrangarh, each panel features intricate floral geometry carved by master generational craftsmen in Jodhpur. Backlit-ready.',
    category: 'Decor',
    dimensions: 'W: 90cm | H: 180cm | Depth: 4.5cm | Weight: 18kg',
    warranty: '15 Years Artisan Guarantee',
    careInstructions: 'Dust gently with a horsehair brush. Avoid chemical cleaners.',
    basePrice: 68000,
    featured: true,
    hsnCode: '9403',
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1582582621959-48d27397dc69?auto=format&fit=crop&w=1200&q=80',
    ]),
    variants: [
      { id: 'vd_3', sku: 'DEC-PAN-TEK-ANT', colorName: 'Antiqued Honey Teak', colorHex: '#8C6239', material: 'Reclaimed CP Teakwood', priceOverride: 68000, stock: 5 },
      { id: 'vd_4', sku: 'DEC-PAN-TEK-WHT', colorName: 'Bleached Coastal Teak', colorHex: '#D5CCA8', material: 'Weathered Teak', priceOverride: 72000, stock: 3 },
    ],
  },
  {
    id: 'dec_3',
    slug: 'aurelius-sheesham-brass-monolith-candleholders',
    name: 'The Aurelius Sheesham & Cast Brass Candelabra Pillars',
    tagline: 'Set of 3 sculptural timber obelisks with solid brushed brass collars',
    description: 'Graduated architectural pedestals crafted from dense Indian Sheesham rosewood, crowned with solid heavy-gauge brass candle wells that accommodate pillar and taper candles.',
    category: 'Decor',
    dimensions: 'Heights: 30cm, 40cm, 50cm | Base: 10x10cm | Set Weight: 5.5kg',
    warranty: '10 Years Structural Guarantee',
    careInstructions: 'Clean brass with dry lint-free cloth. Nourish wood periodically.',
    basePrice: 18500,
    featured: false,
    hsnCode: '9403',
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1603006905003-be475563bc59?auto=format&fit=crop&w=1200&q=80',
    ]),
    variants: [
      { id: 'vd_5', sku: 'DEC-CND-SHS-BRZ', colorName: 'Rosewood & Brass', colorHex: '#4A2A18', material: 'Sheesham & Cast Brass', priceOverride: 18500, stock: 12 },
    ],
  },
  {
    id: 'dec_4',
    slug: 'fluted-monolith-oak-pedestal-plinth',
    name: 'The Corinthian Fluted Oak Display Pedestal',
    tagline: 'Monumental fluted column plinth for art sculptures and bronze urns',
    description: 'Features 32 precision CNC-milled flutes around a solid rift-cut white oak drum, finished with an ultra-matte architectural sealant.',
    category: 'Decor',
    dimensions: 'Diameter: 38cm | H: 100cm | Weight: 26kg | Load Capacity: 120kg',
    warranty: '15 Years Structural Warranty',
    careInstructions: 'Dust with dry microfiber cloth.',
    basePrice: 52000,
    featured: true,
    hsnCode: '9403',
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1595428774223-ef52624120d2?auto=format&fit=crop&w=1200&q=80',
    ]),
    variants: [
      { id: 'vd_6', sku: 'DEC-PLN-OAK-NAT', colorName: 'Natural White Oak', colorHex: '#CDB99C', material: 'Rift-Cut Oak', priceOverride: 52000, stock: 6 },
      { id: 'vd_7', sku: 'DEC-PLN-OAK-BLK', colorName: 'Charred Black Oak', colorHex: '#1C1B1A', material: 'Charred Oak', priceOverride: 54000, stock: 4 },
    ],
  },
  {
    id: 'dec_5',
    slug: 'zen-hinoki-cedar-aroma-diffuser-totem',
    name: 'The Zen Hinoki Aromatic Diffuser Vessel',
    tagline: 'Japanese cypress aroma chamber with concealed ultrasonic mist portal',
    description: 'Crafted from fragrant Japanese Hinoki cypress wood that emits natural phytoncides when heated gently. Features capacitive touch control and warm amber glow.',
    category: 'Decor',
    dimensions: 'W: 16cm | D: 16cm | H: 28cm | Weight: 2.1kg',
    warranty: '3 Years Electronics & Wood Warranty',
    careInstructions: 'Rinse water reservoir weekly. Wipe wooden shell with dry cloth.',
    basePrice: 22000,
    featured: false,
    hsnCode: '9403',
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?auto=format&fit=crop&w=1200&q=80',
    ]),
    variants: [
      { id: 'vd_8', sku: 'DEC-DIF-HNK-NAT', colorName: 'Natural Hinoki', colorHex: '#E2D3B8', material: 'Hinoki Cypress', priceOverride: 22000, stock: 15 },
    ],
  },
  {
    id: 'dec_6',
    slug: 'marwar-carved-rosewood-mirror-frame',
    name: 'The Marwar Grand Arch Rosewood Mirror',
    tagline: 'Palatial floor mirror with hand-carved acanthus crest and beveled Belgian glass',
    description: 'Carved over 120 artisan hours from aged Indian rosewood. The double-beveled 6mm silver mirror reflects light with exceptional clarity.',
    category: 'Decor',
    dimensions: 'W: 100cm | H: 210cm | Frame Thickness: 7cm | Weight: 38kg',
    warranty: '15 Years Artisan Guarantee',
    careInstructions: 'Clean glass with standard glass cleaner. Buff wooden frame with dry flannel.',
    basePrice: 89000,
    featured: true,
    hsnCode: '9403',
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=1200&q=80',
    ]),
    variants: [
      { id: 'vd_9', sku: 'DEC-MIR-RSW-BRN', colorName: 'Heritage Rosewood', colorHex: '#3B1F13', material: 'Solid Rosewood', priceOverride: 89000, stock: 3 },
    ],
  },
  {
    id: 'dec_7',
    slug: 'monolith-charred-oak-bookends-brass',
    name: 'The Monolith Charred Oak & Solid Brass Bookends',
    tagline: 'Pair of heavy architectural L-monoliths with counterbalanced brass inlays',
    description: 'Shou Sugi Ban fire-charred white oak weighted with internal 2kg solid brass plinths. Non-slip suede leather base protects bookshelf finishes.',
    category: 'Decor',
    dimensions: 'W: 14cm | D: 10cm | H: 22cm each | Pair Weight: 4.8kg',
    warranty: '10 Years Structural Guarantee',
    careInstructions: 'Dust with microfibre cloth.',
    basePrice: 16500,
    featured: false,
    hsnCode: '9403',
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=1200&q=80',
    ]),
    variants: [
      { id: 'vd_10', sku: 'DEC-BKE-OAK-BRZ', colorName: 'Charred Oak & Brass', colorHex: '#1B1A18', material: 'Oak & Solid Brass', priceOverride: 16500, stock: 14 },
    ],
  },
  {
    id: 'dec_8',
    slug: 'sculptural-mango-wood-amphora-vase',
    name: 'The Amphora Turned Mango Wood Sculptural Vessel',
    tagline: 'Fluid organic silhouette hand-turned on traditional timber lathes',
    description: 'Sculptural decorative dry vessel showcasing natural spalting lines and character rings of sustainably sourced mango wood.',
    category: 'Decor',
    dimensions: 'Diameter: 28cm | H: 48cm | Weight: 3.4kg',
    warranty: '5 Years Wood Integrity Guarantee',
    careInstructions: 'Suitable for dry floral arrangements and decorative display only.',
    basePrice: 19500,
    featured: false,
    hsnCode: '9403',
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1581783342308-f792dbdd27c5?auto=format&fit=crop&w=1200&q=80',
    ]),
    variants: [
      { id: 'vd_11', sku: 'DEC-VAS-MNG-NAT', colorName: 'Natural Spalted Mango', colorHex: '#CBB28A', material: 'Solid Mango Wood', priceOverride: 19500, stock: 9 },
      { id: 'vd_12', sku: 'DEC-VAS-MNG-WHT', colorName: 'Limewashed White', colorHex: '#EAE5D9', material: 'Limewashed Mango Wood', priceOverride: 21000, stock: 5 },
    ],
  },
  {
    id: 'dec_9',
    slug: 'verona-scalloped-teakwood-valet-tray',
    name: 'The Verona Scalloped Teakwood Valet Tray',
    tagline: 'Machined from solid Burma teak with Italian saddle leather insert',
    description: 'Curvilinear scalloped edges holding an Italian full-grain cognac leather interior. Designed for timepieces, cuff links, and executive essentials.',
    category: 'Decor',
    dimensions: 'L: 36cm | W: 24cm | H: 4cm | Weight: 1.2kg',
    warranty: '5 Years Craftsmanship Warranty',
    careInstructions: 'Wipe leather with dry microfibre cloth.',
    basePrice: 14500,
    featured: false,
    hsnCode: '9403',
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=1200&q=80',
    ]),
    variants: [
      { id: 'vd_13', sku: 'DEC-TRY-TEK-CGN', colorName: 'Teak & Cognac Leather', colorHex: '#844E28', material: 'Burma Teak & Calfskin', priceOverride: 14500, stock: 16 },
    ],
  },
  {
    id: 'dec_10',
    slug: 'celestial-solid-walnut-kinetic-clock',
    name: 'The Celestial Solid Walnut & Brushed Gold Minimalist Clock',
    tagline: 'Concealed silent German quartz movement within a solid walnut halo',
    description: 'An architectural 60cm wall clock featuring precision laser-cut brass index markers and satin gold hands against deep-grained American walnut.',
    category: 'Decor',
    dimensions: 'Diameter: 60cm | Depth: 5cm | Weight: 4.2kg',
    warranty: '5 Years Movement & Wood Guarantee',
    careInstructions: 'Requires 1 AA battery. Dust face with soft dry cloth.',
    basePrice: 28000,
    featured: true,
    hsnCode: '9403',
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1563861826100-9cb868fdbe1c?auto=format&fit=crop&w=1200&q=80',
    ]),
    variants: [
      { id: 'vd_14', sku: 'DEC-CLK-WAL-GLD', colorName: 'Walnut & Brushed Gold', colorHex: '#4E311B', material: 'American Walnut & Brass', priceOverride: 28000, stock: 7 },
    ],
  },
  // Adding items 11 to 50 systematically with rich details
  {
    id: 'dec_11',
    slug: 'solis-geometric-hardwood-obelisk-sculptures',
    name: 'The Solis Geometric Hardwood Obelisks (Set of 2)',
    tagline: 'Architectural faceted sculptures in smoked ash and solid brass',
    description: 'Chiseled multi-faceted geometry inspired by brutalist monumental architecture. Weighted with concealed brass plinths.',
    category: 'Decor',
    dimensions: 'Heights: 38cm and 48cm | Base: 12x12cm | Pair: 4.6kg',
    warranty: '10 Years Guarantee',
    careInstructions: 'Dust with soft feather duster.',
    basePrice: 21500,
    featured: false,
    hsnCode: '9403',
    images: JSON.stringify(['https://images.unsplash.com/photo-1513519245088-0e12902e5a38?auto=format&fit=crop&w=1200&q=80']),
    variants: [{ id: 'vd_15', sku: 'DEC-OBL-ASH-BLK', colorName: 'Smoked Ash', colorHex: '#252321', material: 'Solid Ash Wood', priceOverride: 21500, stock: 8 }],
  },
  {
    id: 'dec_12',
    slug: 'imperial-burled-walnut-watch-chest',
    name: 'The Imperial Burled Walnut 10-Watch Collector Chest',
    tagline: 'High-gloss piano lacquer finish with velvet pillows and brass mortise lock',
    description: 'Crafted from rare California walnut burl veneer over solid hardwood core. Features soft-closing hinges and German lock mechanism.',
    category: 'Decor',
    dimensions: 'W: 34cm | D: 24cm | H: 12cm | Weight: 3.6kg',
    warranty: '10 Years Hardware Warranty',
    careInstructions: 'Polish lacquer with optical cloth only.',
    basePrice: 38500,
    featured: true,
    hsnCode: '9403',
    images: JSON.stringify(['https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=1200&q=80']),
    variants: [{ id: 'vd_16', sku: 'DEC-BOX-BRL-WAL', colorName: 'Walnut Burl Piano Gloss', colorHex: '#643918', material: 'Walnut Burl & Velvet', priceOverride: 38500, stock: 5 }],
  },
  {
    id: 'dec_13',
    slug: 'olympus-sculptural-live-edge-teak-console-tray',
    name: 'The Olympus Live-Edge Teak Long Console Vessel',
    tagline: 'One-metre statement tray preserving natural cambium bark contours',
    description: 'Hand-carved from seasoned CP teak root cross-sections. Each piece features entirely unique natural voids stabilized with clear botanical resin.',
    category: 'Decor',
    dimensions: 'L: 105cm | W: 26cm | H: 8cm | Weight: 5.8kg',
    warranty: '10 Years Guarantee',
    careInstructions: 'Condition quarterly with natural beeswax paste.',
    basePrice: 32000,
    featured: true,
    hsnCode: '9403',
    images: JSON.stringify(['https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?auto=format&fit=crop&w=1200&q=80']),
    variants: [{ id: 'vd_17', sku: 'DEC-TRY-TEK-LVE', colorName: 'Live-Edge Raw Teak', colorHex: '#7B4A21', material: 'Raw Teak Root', priceOverride: 32000, stock: 4 }],
  },
  {
    id: 'dec_14',
    slug: 'fluted-sheesham-magazine-records-tote',
    name: 'The Atelier Fluted Sheesham Magazine & Vinyl Caddy',
    tagline: 'Architectural tambour slatted caddy with burnished bronze handle',
    description: 'Holds up to 30 architectural journals or 12-inch vinyl records in partitioned luxury.',
    category: 'Decor',
    dimensions: 'W: 42cm | D: 26cm | H: 38cm | Weight: 4.5kg',
    warranty: '10 Years Joinery Warranty',
    careInstructions: 'Wipe with damp cloth and dry immediately.',
    basePrice: 22500,
    featured: false,
    hsnCode: '9403',
    images: JSON.stringify(['https://images.unsplash.com/photo-1544457070-4cd773b4d71e?auto=format&fit=crop&w=1200&q=80']),
    variants: [{ id: 'vd_18', sku: 'DEC-CAD-SHS-BRZ', colorName: 'Natural Sheesham & Bronze', colorHex: '#522F19', material: 'Sheesham & Cast Bronze', priceOverride: 22500, stock: 10 }],
  },
  {
    id: 'dec_15',
    slug: 'kyoto-shou-sugi-ban-wall-sculpture',
    name: 'The Kyoto Shou Sugi Ban Charred Wood Wall Triptych',
    tagline: 'Three-panel charred cedar wall relief with geometric gold leaf gilding',
    description: 'Using the ancient 18th-century Japanese Yakisugi technique, solid cedar is flame-treated to create an alligator-texture charcoal patina accented with 24k gold leaf.',
    category: 'Decor',
    dimensions: 'Overall W: 160cm | H: 90cm | Depth: 5cm | Total Weight: 14kg',
    warranty: '15 Years Material Guarantee',
    careInstructions: 'Dust with soft static duster.',
    basePrice: 75000,
    featured: true,
    hsnCode: '9403',
    images: JSON.stringify(['https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&w=1200&q=80']),
    variants: [{ id: 'vd_19', sku: 'DEC-ART-YAK-GLD', colorName: 'Charred Black & Gold Leaf', colorHex: '#141414', material: 'Japanese Yakisugi Cedar', priceOverride: 75000, stock: 3 }],
  },
  {
    id: 'dec_16',
    slug: 'grand-master-walnut-leather-chess-set',
    name: 'The Grandmaster Solid Walnut & Maple Heirloom Chess Cabinet',
    tagline: 'Hand-carved tournament-scale chess set with pull-out velvet drawers',
    description: 'Solid quarter-sawn walnut and rock maple board. 32 weighted, felt-bottomed pieces hand-sculpted by master woodturners.',
    category: 'Decor',
    dimensions: 'Board: 52x52cm | H: 10cm | King Height: 10.5cm | Weight: 7.2kg',
    warranty: 'Lifetime Heirloom Covenant',
    careInstructions: 'Keep in temperate dry environment.',
    basePrice: 48000,
    featured: true,
    hsnCode: '9403',
    images: JSON.stringify(['https://images.unsplash.com/photo-1586165368502-1bad197a6461?auto=format&fit=crop&w=1200&q=80']),
    variants: [{ id: 'vd_20', sku: 'DEC-CHS-WAL-MPL', colorName: 'American Walnut & Maple', colorHex: '#482C17', material: 'Walnut & Maple Hardwood', priceOverride: 48000, stock: 6 }],
  },
  {
    id: 'dec_17',
    slug: 'fluted-teak-floor-lantern-set',
    name: 'The Fluted Burma Teak Architectural Floor Lanterns (Set of 2)',
    tagline: 'Towering candle lanterns with beveled tempered glass panels and brass handles',
    description: 'Graceful architectural lanterns crafted from weather-resistant Burma teak with antiqued brass ventilation crowns.',
    category: 'Decor',
    dimensions: 'Heights: 65cm and 85cm | Base: 24x24cm | Pair Weight: 11kg',
    warranty: '10 Years Structural Guarantee',
    careInstructions: 'Suitable for indoor and covered verandas.',
    basePrice: 36000,
    featured: false,
    hsnCode: '9403',
    images: JSON.stringify(['https://images.unsplash.com/photo-1513519245088-0e12902e5a38?auto=format&fit=crop&w=1200&q=80']),
    variants: [{ id: 'vd_21', sku: 'DEC-LTN-TEK-BRZ', colorName: 'Oiled Burma Teak & Brass', colorHex: '#6F421D', material: 'Teak & Tempered Glass', priceOverride: 36000, stock: 7 }],
  },
  {
    id: 'dec_18',
    slug: 'sculptural-cedar-bath-bridge-caddy',
    name: 'The Sanctuary Solid Aromatic Cedar Bath Bridge',
    tagline: 'Water-impervious cedar tub tray with book prop and wine glass holder',
    description: 'Naturally resistant to moisture and mold. Features precision routed drains and an adjustable solid brass reading easel.',
    category: 'Decor',
    dimensions: 'L: 85cm (expandable to 105cm) | W: 24cm | Weight: 3.2kg',
    warranty: '5 Years Water Integrity Guarantee',
    careInstructions: 'Allow to air dry naturally after soaking.',
    basePrice: 17500,
    featured: false,
    hsnCode: '9403',
    images: JSON.stringify(['https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=1200&q=80']),
    variants: [{ id: 'vd_22', sku: 'DEC-BTH-CDR-NAT', colorName: 'Aromatic Red Cedar', colorHex: '#8E4B2F', material: 'Western Red Cedar', priceOverride: 17500, stock: 12 }],
  },
  {
    id: 'dec_19',
    slug: 'fluted-oak-cylindrical-planters-set',
    name: 'The Corinthian Fluted Oak Architectural Planter Urns (Set of 2)',
    tagline: 'Elevated cylindrical plant pedestals with removable galvanized zinc liners',
    description: 'Rhythmically fluted solid oak planters elevated on three tapered conical feet. Internal drip tray included.',
    category: 'Decor',
    dimensions: 'Large: D: 36cm, H: 55cm | Medium: D: 28cm, H: 42cm | Set: 8.5kg',
    warranty: '5 Years Guarantee',
    careInstructions: 'Use interior zinc liner when watering plants.',
    basePrice: 29500,
    featured: false,
    hsnCode: '9403',
    images: JSON.stringify(['https://images.unsplash.com/photo-1485955900006-10f4d324d411?auto=format&fit=crop&w=1200&q=80']),
    variants: [{ id: 'vd_23', sku: 'DEC-PLT-OAK-NAT', colorName: 'Natural White Oak', colorHex: '#C5B192', material: 'Solid Oak & Zinc', priceOverride: 29500, stock: 9 }],
  },
  {
    id: 'dec_20',
    slug: 'reclaimed-teak-monolith-coat-tree',
    name: 'The Sentry Reclaimed Teak Sculptural Coat & Hat Totem',
    tagline: 'Monumental tree stand with hand-forged blackened iron branch pegs',
    description: 'Hewn from a single reclaimed timber beam with weighted steel plinth foundation. Features 8 staggered coat hooks.',
    category: 'Decor',
    dimensions: 'Base: 36x36cm | H: 185cm | Weight: 24kg',
    warranty: '15 Years Structural Warranty',
    careInstructions: 'Dust regularly.',
    basePrice: 34500,
    featured: false,
    hsnCode: '9403',
    images: JSON.stringify(['https://images.unsplash.com/photo-1586023492125-27b2c045efd7?auto=format&fit=crop&w=1200&q=80']),
    variants: [{ id: 'vd_24', sku: 'DEC-COT-TEK-IRN', colorName: 'Weathered Teak & Forged Iron', colorHex: '#583A22', material: 'Teak & Forged Iron', priceOverride: 34500, stock: 5 }],
  },
  // Items 21 to 50
  {
    id: 'dec_21',
    slug: 'artisan-turned-walnut-table-lamp',
    name: 'The Aurelia Hand-Turned Walnut Column Lamp',
    tagline: 'Solid walnut base with warm brass dimmer switch and raw linen shade',
    description: 'Turned on a heavy timber lathe from kiln-dried American walnut. Fitted with Belgian oatmeal linen conical drum shade and warm 2700K LED bulb.',
    category: 'Decor',
    dimensions: 'Base Diameter: 18cm | Total Height: 62cm | Shade D: 38cm | Weight: 3.8kg',
    warranty: '5 Years Electrical & Wood Guarantee',
    careInstructions: 'Clean shade with soft lint roller.',
    basePrice: 26500,
    featured: true,
    hsnCode: '9403',
    images: JSON.stringify(['https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=1200&q=80']),
    variants: [{ id: 'vd_25', sku: 'DEC-LMP-WAL-LIN', colorName: 'Smoked Walnut & Oatmeal Linen', colorHex: '#432B19', material: 'Walnut, Brass & Linen', priceOverride: 26500, stock: 11 }],
  },
  {
    id: 'dec_22',
    slug: 'carved-rosewood-bone-inlay-trinket-box',
    name: 'The Udaipur Floral Inlay Rosewood Keepsake Box',
    tagline: 'Hand-carved botanical motifs with ethically sourced camel bone inlay',
    description: 'Over 40 hours of master fretwork inlay in rich Indian rosewood with plush burgundy velvet lining and mortise hinge.',
    category: 'Decor',
    dimensions: 'L: 28cm | W: 18cm | H: 10cm | Weight: 1.8kg',
    warranty: '10 Years Craftsmanship Guarantee',
    careInstructions: 'Wipe with dry microfiber cloth.',
    basePrice: 15500,
    featured: false,
    hsnCode: '9403',
    images: JSON.stringify(['https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?auto=format&fit=crop&w=1200&q=80']),
    variants: [{ id: 'vd_26', sku: 'DEC-BOX-RSW-BNE', colorName: 'Rosewood & White Inlay', colorHex: '#3A1B10', material: 'Rosewood & Bone Inlay', priceOverride: 15500, stock: 15 }],
  },
  {
    id: 'dec_23',
    slug: 'fluted-walnut-kleenex-tissue-coffer',
    name: 'The Sovereign Fluted Walnut Tissue Coffer',
    tagline: 'Magnetic bottom-sliding closure in monolithic solid American walnut',
    description: 'Elevates standard tissue boxes into luxury decorative statements with precision fluted vertical relief.',
    category: 'Decor',
    dimensions: 'L: 26cm | W: 14cm | H: 10cm | Weight: 1.1kg',
    warranty: '5 Years Guarantee',
    careInstructions: 'Wipe with dry cloth.',
    basePrice: 9500,
    featured: false,
    hsnCode: '9403',
    images: JSON.stringify(['https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=1200&q=80']),
    variants: [{ id: 'vd_27', sku: 'DEC-TIS-WAL-NAT', colorName: 'Natural Walnut', colorHex: '#55331C', material: 'Solid American Walnut', priceOverride: 9500, stock: 20 }],
  },
  {
    id: 'dec_24',
    slug: 'monolithic-sheesham-wine-collector-cradle',
    name: 'The Bacchus Monolithic Sheesham 8-Bottle Wine Cradle',
    tagline: 'Sculptural horizontal cantilevers holding vintage reserves in alignment',
    description: 'Carved from single dense Sheesham log keeping corks properly angled and aerated in architectural poise.',
    category: 'Decor',
    dimensions: 'W: 55cm | D: 22cm | H: 30cm | Weight: 6.2kg',
    warranty: '10 Years Structural Guarantee',
    careInstructions: 'Dust regularly.',
    basePrice: 23000,
    featured: false,
    hsnCode: '9403',
    images: JSON.stringify(['https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&w=1200&q=80']),
    variants: [{ id: 'vd_28', sku: 'DEC-WIN-SHS-NAT', colorName: 'Heritage Rosewood Finish', colorHex: '#482715', material: 'Solid Indian Sheesham', priceOverride: 23000, stock: 8 }],
  },
  {
    id: 'dec_25',
    slug: 'sculptural-mango-wood-footed-fruit-platter',
    name: 'The Solstice Footed Mango Wood Pedestal Tazza',
    tagline: 'Broad sculptural tazza bowl elevated on tri-footed conical plinths',
    description: 'Organic dished silhouette showcasing natural golden and amber spalting grain. Food-safe botanical wax finish.',
    category: 'Decor',
    dimensions: 'Diameter: 40cm | H: 16cm | Weight: 2.9kg',
    warranty: '5 Years Guarantee',
    careInstructions: 'Wash gently with mild soapy water; dry immediately.',
    basePrice: 18000,
    featured: false,
    hsnCode: '9403',
    images: JSON.stringify(['https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?auto=format&fit=crop&w=1200&q=80']),
    variants: [{ id: 'vd_29', sku: 'DEC-PLT-MNG-NAT', colorName: 'Spalted Golden Mango', colorHex: '#C9A87C', material: 'Solid Mango Wood', priceOverride: 18000, stock: 14 }],
  },
  {
    id: 'dec_26',
    slug: 'petrified-wood-sheesham-coaster-vault',
    name: 'The Continental Petrified Wood & Sheesham Coaster Vault (Set of 6)',
    tagline: 'Fossilized Indonesian wood cross-sections in Sheesham cradle',
    description: 'Millions of years old mineralized petrified timber slices with hand-polished stone finish and cork backing.',
    category: 'Decor',
    dimensions: 'Coaster D: 10cm | Vault: 12x12x8cm | Weight: 1.9kg',
    warranty: '10 Years Guarantee',
    careInstructions: 'Wipe coasters with damp cloth.',
    basePrice: 12500,
    featured: false,
    hsnCode: '9403',
    images: JSON.stringify(['https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?auto=format&fit=crop&w=1200&q=80']),
    variants: [{ id: 'vd_30', sku: 'DEC-CST-PTR-WOD', colorName: 'Petrified Mineral & Sheesham', colorHex: '#685444', material: 'Petrified Wood & Sheesham', priceOverride: 12500, stock: 18 }],
  },
  {
    id: 'dec_27',
    slug: 'hand-chiseled-teakwood-wall-sconces',
    name: 'The Veritas Fluted Teak & Smoked Glass Wall Sconces (Pair)',
    tagline: 'Warm architectural ambient wall luminaires in solid CP teak',
    description: 'Hardwired architectural wall lights with hand-beveled teak backplates and mouth-blown smoked glass hurricane tubes.',
    category: 'Decor',
    dimensions: 'W: 14cm | H: 45cm | Projection: 16cm each | Pair: 4.8kg',
    warranty: '5 Years Electrical & Wood Warranty',
    careInstructions: 'Standard 220V E27 LED bulb compatible.',
    basePrice: 32500,
    featured: false,
    hsnCode: '9403',
    images: JSON.stringify(['https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=1200&q=80']),
    variants: [{ id: 'vd_31', sku: 'DEC-SCN-TEK-GLS', colorName: 'Burma Teak & Smoked Glass', colorHex: '#643C1E', material: 'Teak & Smoked Glass', priceOverride: 32500, stock: 7 }],
  },
  {
    id: 'dec_28',
    slug: 'solid-walnut-book-display-easel',
    name: 'The Monograph Solid Walnut Architectural Book Stand',
    tagline: 'Adjustable reading incline for oversized art monographs and collectors albums',
    description: 'Precision brass pivoting hinge supporting heavy oversized Taschen and Assouline volumes with grace.',
    category: 'Decor',
    dimensions: 'W: 38cm | D: 28cm | H: 22cm | Weight: 2.4kg',
    warranty: '10 Years Joinery Warranty',
    careInstructions: 'Dust with soft cloth.',
    basePrice: 16000,
    featured: false,
    hsnCode: '9403',
    images: JSON.stringify(['https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=1200&q=80']),
    variants: [{ id: 'vd_32', sku: 'DEC-ESL-WAL-BRZ', colorName: 'American Walnut & Brass', colorHex: '#4E301A', material: 'American Walnut & Brass', priceOverride: 16000, stock: 12 }],
  },
  {
    id: 'dec_29',
    slug: 'sculptural-carved-teak-mortar-pestle',
    name: 'The Sovereign Monumental Carved Teak Mortar Vessel',
    tagline: 'Sculptural kitchen & table centerpiece carved from aged teak trunk',
    description: 'An oversized statement decor piece with hand-chiseled rustic ridges and polished pestle talisman.',
    category: 'Decor',
    dimensions: 'Diameter: 26cm | H: 24cm | Pestle L: 28cm | Weight: 4.1kg',
    warranty: '10 Years Wood Guarantee',
    careInstructions: 'Condition with food-grade mineral oil.',
    basePrice: 19000,
    featured: false,
    hsnCode: '9403',
    images: JSON.stringify(['https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?auto=format&fit=crop&w=1200&q=80']),
    variants: [{ id: 'vd_33', sku: 'DEC-MOR-TEK-NAT', colorName: 'Natural Aged Teak', colorHex: '#714B2C', material: 'Solid CP Teak', priceOverride: 19000, stock: 9 }],
  },
  {
    id: 'dec_30',
    slug: 'geometric-wooden-decorative-spheres-trio',
    name: 'The Celestial Hand-Turned Hardwood Spheres (Set of 3)',
    tagline: 'Solid turned spheres in Walnut, Rosewood, and Oak with brass ring stands',
    description: 'Perfect geometric spheres hand-turned to 0.5mm precision resting on heavy solid brass seating rings.',
    category: 'Decor',
    dimensions: 'Diameters: 12cm, 15cm, 18cm | Set Weight: 4.5kg',
    warranty: '10 Years Guarantee',
    careInstructions: 'Dust with soft microfibre.',
    basePrice: 21000,
    featured: false,
    hsnCode: '9403',
    images: JSON.stringify(['https://images.unsplash.com/photo-1513519245088-0e12902e5a38?auto=format&fit=crop&w=1200&q=80']),
    variants: [{ id: 'vd_34', sku: 'DEC-SPH-TRI-BRZ', colorName: 'Trio Woods & Brass', colorHex: '#5A3822', material: 'Walnut, Rosewood, Oak & Brass', priceOverride: 21000, stock: 10 }],
  },
  // Items 31 to 50
  {
    id: 'dec_31',
    slug: 'sheesham-brass-inlaid-cutlery-canteen',
    name: 'The Royal Durbar Sheesham Silverware Canteen Chest',
    tagline: 'Anti-tarnish velvet interior with brass corner strapping and double latches',
    description: 'Custom fitted for 72-piece sterling silver dining sets with lockable key latch.',
    category: 'Decor',
    dimensions: 'L: 48cm | W: 36cm | H: 18cm | Weight: 6.5kg',
    warranty: '15 Years Hardware & Joinery Guarantee',
    careInstructions: 'Polish brass with dry cloth.',
    basePrice: 34000,
    featured: false,
    hsnCode: '9403',
    images: JSON.stringify(['https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=1200&q=80']),
    variants: [{ id: 'vd_35', sku: 'DEC-CNT-SHS-BRS', colorName: 'Rich Sheesham & Brass', colorHex: '#4E2B18', material: 'Sheesham & Brass', priceOverride: 34000, stock: 6 }],
  },
  {
    id: 'dec_32',
    slug: 'monolithic-reclaimed-railway-sleeper-riser',
    name: 'The Heritage Reclaimed Timber Pedestal Plinth Riser',
    tagline: '100-year-old salvaged railway sal timber with deep weathered grain',
    description: 'Dense historical timber wire-brushed and sealed with matte polyurethane for books, candles, or sculpture risers.',
    category: 'Decor',
    dimensions: 'L: 60cm | W: 22cm | H: 14cm | Weight: 12kg',
    warranty: '20 Years Timber Guarantee',
    careInstructions: 'Dust with soft brush.',
    basePrice: 19500,
    featured: false,
    hsnCode: '9403',
    images: JSON.stringify(['https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?auto=format&fit=crop&w=1200&q=80']),
    variants: [{ id: 'vd_36', sku: 'DEC-RSR-SLP-NAT', colorName: 'Ancient Weathered Sal', colorHex: '#42372E', material: 'Reclaimed Sal Timber', priceOverride: 19500, stock: 7 }],
  },
  {
    id: 'dec_33',
    slug: 'sculptural-wave-fluted-wall-mirror',
    name: 'The Onda Undulating Fluted Oak Wall Mirror',
    tagline: 'Organic wave-form carved solid oak frame with distortion-free mirror',
    description: 'Sculptural carved wave perimeter creating dynamic shadow lines on gallery walls.',
    category: 'Decor',
    dimensions: 'Diameter: 85cm | Depth: 6cm | Weight: 12kg',
    warranty: '10 Years Glass & Frame Warranty',
    careInstructions: 'Clean mirror with standard glass spray.',
    basePrice: 42000,
    featured: true,
    hsnCode: '9403',
    images: JSON.stringify(['https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=1200&q=80']),
    variants: [{ id: 'vd_37', sku: 'DEC-MIR-OND-OAK', colorName: 'Natural Wave Oak', colorHex: '#C6B296', material: 'Solid Oak & Silver Glass', priceOverride: 42000, stock: 5 }],
  },
  {
    id: 'dec_34',
    slug: 'artisan-carved-teak-door-handle-pulls',
    name: 'The Sovereign Sculptural Teak & Brass Door Pulls (Pair)',
    tagline: '60cm palatial entrance door handles carved from monolithic Burma teak',
    description: 'Ergonomic sculptured handles with solid brass mounting posts for luxury entrance doors and heavy pivot portals.',
    category: 'Decor',
    dimensions: 'Length: 60cm | Thickness: 5cm | Pair Weight: 3.8kg',
    warranty: '15 Years Hardware Warranty',
    careInstructions: 'Wipe with dry microfiber cloth.',
    basePrice: 28000,
    featured: false,
    hsnCode: '9403',
    images: JSON.stringify(['https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=1200&q=80']),
    variants: [{ id: 'vd_38', sku: 'DEC-HDL-TEK-BRS', colorName: 'Burma Teak & Solid Brass', colorHex: '#724B28', material: 'Burma Teak & Brass', priceOverride: 28000, stock: 11 }],
  },
  {
    id: 'dec_35',
    slug: 'minimalist-walnut-desk-tote-organizer',
    name: 'The Monograph Minimalist Walnut Desk Station',
    tagline: 'Integrated slots for tablet, pens, stationery with wireless charging conduit',
    description: 'Precision milled from American black walnut with black calfskin phone rest.',
    category: 'Decor',
    dimensions: 'L: 32cm | W: 18cm | H: 5cm | Weight: 1.1kg',
    warranty: '5 Years Guarantee',
    careInstructions: 'Dust with soft cloth.',
    basePrice: 13500,
    featured: false,
    hsnCode: '9403',
    images: JSON.stringify(['https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=1200&q=80']),
    variants: [{ id: 'vd_39', sku: 'DEC-DSK-WAL-LTH', colorName: 'Black Walnut & Calfskin', colorHex: '#4A2F1D', material: 'Walnut & Leather', priceOverride: 13500, stock: 16 }],
  },
  {
    id: 'dec_36',
    slug: 'fluted-sheesham-umbrella-stand-brass',
    name: 'The Foyer Fluted Sheesham Umbrella Plinth',
    tagline: 'Cylindrical fluted umbrella urn with removable brass water-catch tray',
    description: 'Prevents entryway water pooling with solid brass interior drip saucer and heavy weighted base.',
    category: 'Decor',
    dimensions: 'Diameter: 24cm | H: 58cm | Weight: 7.8kg',
    warranty: '10 Years Structural Guarantee',
    careInstructions: 'Empty and dry internal brass tray after heavy rain.',
    basePrice: 24000,
    featured: false,
    hsnCode: '9403',
    images: JSON.stringify(['https://images.unsplash.com/photo-1595428774223-ef52624120d2?auto=format&fit=crop&w=1200&q=80']),
    variants: [{ id: 'vd_40', sku: 'DEC-UMB-SHS-BRS', colorName: 'Dark Sheesham & Brass', colorHex: '#452718', material: 'Sheesham & Cast Brass', priceOverride: 24000, stock: 8 }],
  },
  {
    id: 'dec_37',
    slug: 'hand-sculpted-solid-cedar-meditation-bench',
    name: 'The Zen Seiza Ergonomic Cedar Meditation Stool',
    tagline: 'Angled ergonomic floating kneeling stool in aromatic Western red cedar',
    description: 'Folds flat with precision hidden wooden mortise hinges for mindful posture alignment.',
    category: 'Decor',
    dimensions: 'W: 46cm | D: 18cm | H: 18cm | Weight: 1.9kg',
    warranty: '10 Years Guarantee',
    careInstructions: 'Aroma can be refreshed by gentle light sanding.',
    basePrice: 14000,
    featured: false,
    hsnCode: '9403',
    images: JSON.stringify(['https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1200&q=80']),
    variants: [{ id: 'vd_41', sku: 'DEC-BNH-CDR-NAT', colorName: 'Aromatic Red Cedar', colorHex: '#8C482C', material: 'Western Red Cedar', priceOverride: 14000, stock: 15 }],
  },
  {
    id: 'dec_38',
    slug: 'artisan-carved-mango-wood-dough-bowl',
    name: 'The Provencal Grand Mango Wood Dough Trench Bowl',
    tagline: '1.1-meter long centerpiece trench bowl with rustic hand-hewn marks',
    description: 'Substantial dining table statement piece for seasonal fruit displays, pinecones, or botanical arrangements.',
    category: 'Decor',
    dimensions: 'L: 110cm | W: 24cm | H: 12cm | Weight: 4.8kg',
    warranty: '5 Years Guarantee',
    careInstructions: 'Wipe with dry or damp cloth.',
    basePrice: 22000,
    featured: false,
    hsnCode: '9403',
    images: JSON.stringify(['https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?auto=format&fit=crop&w=1200&q=80']),
    variants: [{ id: 'vd_42', sku: 'DEC-DGH-MNG-NAT', colorName: 'Natural Hewn Mango', colorHex: '#C5A67B', material: 'Solid Mango Wood', priceOverride: 22000, stock: 10 }],
  },
  {
    id: 'dec_39',
    slug: 'reclaimed-teak-architectural-corbel-shelves',
    name: 'The Rajasthan Heritage Carved Teak Wall Corbels (Pair)',
    tagline: 'Pair of antique floral brackets supporting floating display ledge',
    description: 'Salved architectural temple corbels converted into heirloom wall display brackets.',
    category: 'Decor',
    dimensions: 'W: 16cm | Depth: 22cm | H: 38cm each | Pair: 6.8kg',
    warranty: '15 Years Artisan Guarantee',
    careInstructions: 'Includes heavy-duty concealed wall anchors.',
    basePrice: 27500,
    featured: false,
    hsnCode: '9403',
    images: JSON.stringify(['https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=1200&q=80']),
    variants: [{ id: 'vd_43', sku: 'DEC-CRB-TEK-ANT', colorName: 'Distressed Antique Teak', colorHex: '#694527', material: 'Reclaimed Teakwood', priceOverride: 27500, stock: 6 }],
  },
  {
    id: 'dec_40',
    slug: 'fluted-solid-walnut-waste-receptacle',
    name: 'The Executive Fluted Walnut Waste Paper Urn',
    tagline: 'Architectural fluted cylinder with removable leakproof metal liner',
    description: 'Bespoke study waste bin crafted from quarter-sawn American walnut with brass rim.',
    category: 'Decor',
    dimensions: 'Diameter: 24cm | H: 34cm | Weight: 3.4kg',
    warranty: '10 Years Joinery Guarantee',
    careInstructions: 'Empty and wipe interior liner.',
    basePrice: 17500,
    featured: false,
    hsnCode: '9403',
    images: JSON.stringify(['https://images.unsplash.com/photo-1595428774223-ef52624120d2?auto=format&fit=crop&w=1200&q=80']),
    variants: [{ id: 'vd_44', sku: 'DEC-BIN-WAL-BRS', colorName: 'Black Walnut & Brass Rim', colorHex: '#4C2F1C', material: 'Walnut & Zinc Liner', priceOverride: 17500, stock: 14 }],
  },
  {
    id: 'dec_41',
    slug: 'sculptural-teak-root-abstract-torso',
    name: 'The Form Sculptural Teak Root Abstract Monolith',
    tagline: 'Museum-grade natural root formation mounted on matte black steel pedestal',
    description: 'Each natural teak root sculpture is selected for its dynamic aerodynamic silhouette and hand-sanded to satin smoothness.',
    category: 'Decor',
    dimensions: 'W: 35cm | H: 75cm | Base: 20x20cm | Weight: 8.5kg',
    warranty: 'Lifetime Natural Integrity Guarantee',
    careInstructions: 'Dust with soft dry brush.',
    basePrice: 46000,
    featured: true,
    hsnCode: '9403',
    images: JSON.stringify(['https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?auto=format&fit=crop&w=1200&q=80']),
    variants: [{ id: 'vd_45', sku: 'DEC-ROT-TEK-STL', colorName: 'Natural Teak & Black Steel', colorHex: '#6E4729', material: 'Teak Root & Steel', priceOverride: 46000, stock: 3 }],
  },
  {
    id: 'dec_42',
    slug: 'carved-rosewood-jewelry-armoury-box',
    name: 'The Rani Double-Tier Rosewood Jewelry Coffer',
    tagline: 'Velvet tiered compartments, ring rolls, and brass side lifting handles',
    description: 'Hand-assembled mortise cabinetry with anti-tarnish micro-suede lining throughout.',
    category: 'Decor',
    dimensions: 'L: 32cm | W: 22cm | H: 16cm | Weight: 3.2kg',
    warranty: '10 Years Hardware Warranty',
    careInstructions: 'Wipe with dry cloth.',
    basePrice: 28500,
    featured: false,
    hsnCode: '9403',
    images: JSON.stringify(['https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=1200&q=80']),
    variants: [{ id: 'vd_46', sku: 'DEC-JWL-RSW-BRS', colorName: 'Heritage Rosewood & Brass', colorHex: '#452214', material: 'Rosewood & Brass', priceOverride: 28500, stock: 7 }],
  },
  {
    id: 'dec_43',
    slug: 'fluted-solid-oak-taper-candle-candelabra',
    name: 'The Solarium Fluted Oak 5-Light Taper Candelabra',
    tagline: 'Linear horizontal centerpiece with 5 brass taper candle inserts',
    description: 'Long low-profile dining table centerpiece allowing clear conversational sightlines.',
    category: 'Decor',
    dimensions: 'L: 65cm | W: 10cm | H: 8cm | Weight: 2.8kg',
    warranty: '5 Years Guarantee',
    careInstructions: 'Standard 2.2cm taper candles compatible.',
    basePrice: 19500,
    featured: false,
    hsnCode: '9403',
    images: JSON.stringify(['https://images.unsplash.com/photo-1603006905003-be475563bc59?auto=format&fit=crop&w=1200&q=80']),
    variants: [{ id: 'vd_47', sku: 'DEC-CND-OAK-BRS', colorName: 'Natural Oak & Brass', colorHex: '#CBB493', material: 'Oak & Brass', priceOverride: 19500, stock: 12 }],
  },
  {
    id: 'dec_44',
    slug: 'hand-turned-teak-pillar-candle-pedestals',
    name: 'The Pantheon Hand-Turned Teak Pillar Pedestals (Trio)',
    tagline: 'Three sculptural baluster pillars in rich golden Burma teak',
    description: 'Graduated height trio for mantelpieces and console credenzas.',
    category: 'Decor',
    dimensions: 'Heights: 25cm, 35cm, 45cm | Base D: 12cm | Set: 4.8kg',
    warranty: '10 Years Guarantee',
    careInstructions: 'Clean wax residue gently with plastic card.',
    basePrice: 22500,
    featured: false,
    hsnCode: '9403',
    images: JSON.stringify(['https://images.unsplash.com/photo-1603006905003-be475563bc59?auto=format&fit=crop&w=1200&q=80']),
    variants: [{ id: 'vd_48', sku: 'DEC-PIL-TEK-TR3', colorName: 'Golden Burma Teak', colorHex: '#7C4F2A', material: 'Solid Burma Teak', priceOverride: 22500, stock: 9 }],
  },
  {
    id: 'dec_45',
    slug: 'sculptural-solid-walnut-serving-board',
    name: 'The Sovereign Fluted Walnut Charcuterie & Tasting Paddle',
    tagline: '1-meter long banquet board with fluted handle and leather hanging thong',
    description: 'Quarter-sawn American walnut seasoned and treated with organic botanical oils.',
    category: 'Decor',
    dimensions: 'L: 95cm | W: 24cm | Thickness: 3cm | Weight: 3.1kg',
    warranty: '5 Years Wood Warranty',
    careInstructions: 'Wash with warm water and soap; oil monthly.',
    basePrice: 16500,
    featured: false,
    hsnCode: '9403',
    images: JSON.stringify(['https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=1200&q=80']),
    variants: [{ id: 'vd_49', sku: 'DEC-BRD-WAL-LTH', colorName: 'Dark American Walnut', colorHex: '#482D1B', material: 'Walnut & Leather', priceOverride: 16500, stock: 15 }],
  },
  {
    id: 'dec_46',
    slug: 'antique-sal-wood-wall-clock-monolith',
    name: 'The Horology Reclaimed Sal Wood & Iron Wall Clock',
    tagline: '75cm diameter square frame with exposed hand-welded iron numerals',
    description: 'Weathered railway sal wood backing with hand-forged wrought iron clock ring and silent high-torque German quartz movement.',
    category: 'Decor',
    dimensions: 'W: 75cm | H: 75cm | Depth: 6cm | Weight: 9.8kg',
    warranty: '5 Years Movement & Wood Warranty',
    careInstructions: 'Requires 1 AA battery.',
    basePrice: 38000,
    featured: true,
    hsnCode: '9403',
    images: JSON.stringify(['https://images.unsplash.com/photo-1563861826100-9cb868fdbe1c?auto=format&fit=crop&w=1200&q=80']),
    variants: [{ id: 'vd_50', sku: 'DEC-CLK-SAL-IRN', colorName: 'Antique Sal & Black Iron', colorHex: '#3D342C', material: 'Reclaimed Sal & Iron', priceOverride: 38000, stock: 4 }],
  },
  {
    id: 'dec_47',
    slug: 'zen-cypress-incense-burner-altar',
    name: 'The Altar Japanese Cypress & Brass Incense Shrine',
    tagline: 'Linear smoke-channel burner with brass ash catcher and storage chamber',
    description: 'Engineered for mess-free incense burning with aromatic cypress aroma and concealed 50-stick storage compartment below.',
    category: 'Decor',
    dimensions: 'L: 32cm | W: 8cm | H: 6cm | Weight: 0.9kg',
    warranty: '5 Years Guarantee',
    careInstructions: 'Wipe brass plate with dry cloth.',
    basePrice: 11500,
    featured: false,
    hsnCode: '9403',
    images: JSON.stringify(['https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?auto=format&fit=crop&w=1200&q=80']),
    variants: [{ id: 'vd_51', sku: 'DEC-INC-CYP-BRS', colorName: 'Natural Cypress & Brass', colorHex: '#DECBB0', material: 'Cypress Wood & Brass', priceOverride: 11500, stock: 22 }],
  },
  {
    id: 'dec_48',
    slug: 'sculptural-mango-wood-knot-figurine',
    name: 'The Infinity Hand-Carved Hardwood Loop Sculpture',
    tagline: 'Continuous unbroken Mobius loop hand-chiseled from a single timber block',
    description: 'An impossible mathematical wood carving requiring 24 continuous hours of hand rasping and contour sanding.',
    category: 'Decor',
    dimensions: 'W: 24cm | D: 16cm | H: 28cm | Weight: 2.1kg',
    warranty: '10 Years Guarantee',
    careInstructions: 'Dust with soft microfibre cloth.',
    basePrice: 18500,
    featured: false,
    hsnCode: '9403',
    images: JSON.stringify(['https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&w=1200&q=80']),
    variants: [{ id: 'vd_52', sku: 'DEC-KNT-MNG-NAT', colorName: 'Natural Mango Wood', colorHex: '#C5A982', material: 'Solid Mango Wood', priceOverride: 18500, stock: 11 }],
  },
  {
    id: 'dec_49',
    slug: 'sheesham-brass-decorative-compass-box',
    name: 'The Navigator Vintage Solid Sheesham & Marine Brass Compass',
    tagline: 'Dampened gimballed brass magnetic compass encased in aged rosewood',
    description: 'Handcrafted nautical keepsake with functional floating compass dial and inlaid brass anchor plaque.',
    category: 'Decor',
    dimensions: 'L: 16cm | W: 16cm | H: 9cm | Weight: 1.6kg',
    warranty: '5 Years Guarantee',
    careInstructions: 'Keep dry.',
    basePrice: 14500,
    featured: false,
    hsnCode: '9403',
    images: JSON.stringify(['https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=1200&q=80']),
    variants: [{ id: 'vd_53', sku: 'DEC-CMP-SHS-BRS', colorName: 'Sheesham & Polished Brass', colorHex: '#4A2816', material: 'Sheesham & Brass', priceOverride: 14500, stock: 17 }],
  },
  {
    id: 'dec_50',
    slug: 'fluted-burma-teak-coat-rack-rail',
    name: 'The Foyer Fluted Burma Teak 6-Peg Wall Rail',
    tagline: '1.2-meter architectural wall rail with solid antiqued brass fold-down hooks',
    description: 'Crafted from fluted Burma teak with spring-loaded brass pegs that fold flush when not in use.',
    category: 'Decor',
    dimensions: 'L: 120cm | H: 14cm | Depth: 4cm | Weight: 4.6kg',
    warranty: '15 Years Guarantee',
    careInstructions: 'Heavy duty wall anchor kit included.',
    basePrice: 26000,
    featured: true,
    hsnCode: '9403',
    images: JSON.stringify(['https://images.unsplash.com/photo-1586023492125-27b2c045efd7?auto=format&fit=crop&w=1200&q=80']),
    variants: [{ id: 'vd_54', sku: 'DEC-RIL-TEK-BRS', colorName: 'Burma Teak & Fold Brass', colorHex: '#6F4522', material: 'Burma Teak & Brass', priceOverride: 26000, stock: 8 }],
  },
];
